# Generated by Django 6.0.5 on 2026-07-16 22:19

import apps.identity.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_verification_demand_verified_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Verification_demand",
            new_name="VerificationDemand",
        ),
        migrations.RenameModel(
            old_name="Verified_id",
            new_name="VerifiedId",
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.identity.accounts.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_verified",
            new_name="is_email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nif",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nin",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nin", models.CharField(max_length=18, null=True)),
                ("nif", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
