# Generated by Django 6.0.5 on 2026-09-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="business_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_wilaya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.wilaya",
            ),
        ),
    ]
