name: Backend CI

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    env:
        POSTGRES_DB: bazzari
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        DJANGO_SECRET_KEY: 2026
        DEBUG: True
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
    steps:
      
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          cd backend
          pip install -r requirements.txt

      - run: |
          cd backend
          python manage.py check